// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_sideaton.Models;

namespace Mission06_sideaton.Migrations
{
    [DbContext(typeof(MovieDatabaseContext))]
    [Migration("20230222032002_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_sideaton.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Fantasy"
                        });
                });

            modelBuilder.Entity("Mission06_sideaton.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieDirector")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieRating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MovieYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 1,
                            Edited = false,
                            LentTo = "",
                            MovieDirector = "Joe Wright",
                            MovieRating = "PG",
                            MovieTitle = "Pride & Prejudice",
                            MovieYear = 2005,
                            Notes = ""
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 1,
                            Edited = false,
                            LentTo = "",
                            MovieDirector = "Brenda Chapman",
                            MovieRating = "PG",
                            MovieTitle = "Prince of Egypt",
                            MovieYear = 1998,
                            Notes = ""
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 2,
                            Edited = false,
                            LentTo = "",
                            MovieDirector = "Hayao Miyazaki",
                            MovieRating = "PG",
                            MovieTitle = "Howl's Moving Castle",
                            MovieYear = 2004,
                            Notes = ""
                        });
                });

            modelBuilder.Entity("Mission06_sideaton.Models.Movie", b =>
                {
                    b.HasOne("Mission06_sideaton.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
